name: Build, Test & Deploy
run-name: Building, Testing & Deploying
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - run: npm i -g @angular/cli
      - run: ng build
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - run: npm i -g @angular/cli
      - run: ng test  
      
  deploy:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm i -g @angular/cli
      - run: ng deploy --base-href=/gh-actions-tour-of-heroes/ --name="MSHoekstra" --email="Max.Hoekstra@topicus.nl" --no-silent
