name: Build, Test & Deploy
run-name: Building, Testing & Deploying
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm i -g @angular/cli
      - run: ng build
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm i -g @angular/cli
      - run: ng test
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "to be deployed"
