name: my-first-action
run-name: ${{ github.repository_owner }} is the owner!
on: [push]
jobs:
  run-when-pr-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  
  new-job:
    runs-on: ubuntu-latest
    steps:
      - run: $echo "this is a test on windows"
